/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package p10516133;

/**
 *
 * @author Mahasiswa
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

public class FPeminjaman extends javax.swing.JFrame {
Connection conn;
public DefaultTableModel tabModel;
    /**
     * Creates new form FPeminjaman
     */
    public FPeminjaman() {
        initComponents();
        setJTable();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        peminjaman1 = new p10516133.peminjaman();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        NoPinjam = new javax.swing.JLabel();
        NoAnggota = new javax.swing.JLabel();
        Nama = new javax.swing.JLabel();
        txtNoPinjam = new javax.swing.JTextField();
        txtNoAnggota = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        TglPinjam = new javax.swing.JLabel();
        txtTglPinjam = new javax.swing.JTextField();
        KodeBuku = new javax.swing.JLabel();
        Judul = new javax.swing.JLabel();
        Status = new javax.swing.JLabel();
        txtKodeBuku = new javax.swing.JTextField();
        txtJudulBuku = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        BTambah = new javax.swing.JButton();
        BHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TPinjam = new javax.swing.JTable();
        BTambah1 = new javax.swing.JButton();
        BSimpan = new javax.swing.JButton();
        BBatal = new javax.swing.JButton();
        BClose = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        peminjaman2 = new p10516133.peminjaman();

        javax.swing.GroupLayout peminjaman1Layout = new javax.swing.GroupLayout(peminjaman1);
        peminjaman1.setLayout(peminjaman1Layout);
        peminjaman1Layout.setHorizontalGroup(
            peminjaman1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        peminjaman1Layout.setVerticalGroup(
            peminjaman1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TPP1A-10_10516133_Gania Aldi Darmaditya");

        jPanel1.setBackground(new java.awt.Color(202, 141, 83));

        jLabel3.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(81, 59, 38));
        jLabel3.setText("Form Peminjaman");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(167, 167, 167))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(220, 155, 91));

        NoPinjam.setText("NoPinjam");

        NoAnggota.setText("NoAnggota");

        Nama.setText("Nama");

        txtNoPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoPinjamActionPerformed(evt);
            }
        });

        txtNoAnggota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNoAnggotaKeyPressed(evt);
            }
        });

        txtNama.setEnabled(false);

        TglPinjam.setText("Tgl Pinjam");

        txtTglPinjam.setEnabled(false);

        KodeBuku.setText("Kode Buku");

        Judul.setText("Judul");

        Status.setText("Status");

        txtKodeBuku.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKodeBukuKeyPressed(evt);
            }
        });

        txtJudulBuku.setEnabled(false);

        txtStatus.setEnabled(false);

        BTambah.setText("Tambah");
        BTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTambahActionPerformed(evt);
            }
        });

        BHapus.setText("Hapus");
        BHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHapusActionPerformed(evt);
            }
        });

        TPinjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TPinjam);

        BTambah1.setText("Peminjaman");
        BTambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTambah1ActionPerformed(evt);
            }
        });

        BSimpan.setText("Simpan");
        BSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSimpanActionPerformed(evt);
            }
        });

        BBatal.setText("Batal");
        BBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBatalActionPerformed(evt);
            }
        });

        BClose.setText("Close");
        BClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCloseActionPerformed(evt);
            }
        });

        jButton1.setText("Preview");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        peminjaman2.setBackground(new java.awt.Color(220, 155, 91));

        javax.swing.GroupLayout peminjaman2Layout = new javax.swing.GroupLayout(peminjaman2);
        peminjaman2.setLayout(peminjaman2Layout);
        peminjaman2Layout.setHorizontalGroup(
            peminjaman2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 74, Short.MAX_VALUE)
        );
        peminjaman2Layout.setVerticalGroup(
            peminjaman2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 67, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(NoAnggota)
                                        .addGap(22, 22, 22)
                                        .addComponent(txtNoAnggota))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(NoPinjam)
                                        .addGap(32, 32, 32)
                                        .addComponent(txtNoPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(Status)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(TglPinjam)
                                                .addGap(41, 41, 41)
                                                .addComponent(txtTglPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(37, 37, 37))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(BTambah1)
                                        .addGap(61, 61, 61))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Judul)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Nama)
                                            .addComponent(KodeBuku))
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtKodeBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNama)
                                            .addComponent(txtJudulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(BTambah)
                                        .addGap(18, 18, 18)
                                        .addComponent(BHapus)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BBatal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BClose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(peminjaman2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NoPinjam)
                    .addComponent(txtNoPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TglPinjam)
                    .addComponent(txtTglPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NoAnggota)
                    .addComponent(txtNoAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTambah1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nama)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KodeBuku)
                    .addComponent(Status)
                    .addComponent(txtKodeBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Judul)
                            .addComponent(txtJudulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTambah)
                            .addComponent(BHapus)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BSimpan)
                            .addComponent(BBatal)
                            .addComponent(BClose))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(peminjaman2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNoPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoPinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoPinjamActionPerformed

    private void BTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTambahActionPerformed
        // TODO add your handling code here:
        String KodeBuku;
        boolean ketemu=false;

        int jum=tabModel.getRowCount();
        if(txtStatus.getText().equalsIgnoreCase("Ada")){

            for(int i=0;i<jum;i++){
                KodeBuku = tabModel.getValueAt(i, 0).toString();
                if(KodeBuku.equalsIgnoreCase(txtKodeBuku.getText())){
                    JOptionPane.showMessageDialog(this,"Buku Sudah Ada Pada List Pinjaman");
                    ketemu=true;
                    TPinjam.setRowSelectionInterval(i, i);
                    break;}
            }
            if (ketemu==false) {
                String Data[]={txtKodeBuku.getText(),txtJudulBuku.getText()};
                tabModel.addRow(Data);

                txtKodeBuku.setText("");
                txtJudulBuku.setText("");
                txtStatus.setText("");
            }
        } else
            JOptionPane.showMessageDialog(this, "Buku ini sedang dipinjam","Informasi",JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_BTambahActionPerformed

    private void txtNoAnggotaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoAnggotaKeyPressed
        // TODO add your handling code here:
                if (evt.getKeyCode()==10){
            try {
                Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                conn=DriverManager.getConnection("jdbc:odbc:TPP10");
                String sql="select * from Anggota Where NoAnggota=?";
                PreparedStatement st=conn.prepareStatement(sql);
                st.setString(1,txtNoAnggota.getText());
                ResultSet rs= st.executeQuery();
                if( rs.next()){
                    String Nama = rs.getString("Nama");
                    txtNama.setText(Nama);
                } else{
                    JOptionPane.showMessageDialog(this, "No Anggota Tidak  Ada","Informasi",JOptionPane.INFORMATION_MESSAGE);
                    txtNama.setText("");
                }
            } // akhir try
            catch(Exception e){
                System.out.println("Koneksi Gagal " +e.getMessage());
            }
        }
    // Akhir Event

    }//GEN-LAST:event_txtNoAnggotaKeyPressed

    private void txtKodeBukuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKodeBukuKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==10){           
      try {
      Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
      conn=DriverManager.getConnection("jdbc:odbc:TPP10");
      String sql="select * from Buku Where KodeBuku=?";
      PreparedStatement st=conn.prepareStatement(sql);
      st.setString(1,txtKodeBuku.getText());
      ResultSet rs= st.executeQuery();

      if( rs.next()){
      String JudulBuku = rs.getString("JudulBuku");
      String Status = rs.getString("Status");
      txtJudulBuku.setText(JudulBuku);
      txtStatus.setText(Status);
      }else
      {
      JOptionPane.showMessageDialog(this, "Kode Buku Tidak Ada","Informasi",JOptionPane.INFORMATION_MESSAGE);
      txtJudulBuku.setText("");
      txtStatus.setText("");
      }
      } // akhir try
        catch(Exception e){
           System.out.println("Exception :  " +e);
        }
    }

    }//GEN-LAST:event_txtKodeBukuKeyPressed

    private void BHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHapusActionPerformed
        // TODO add your handling code here:
                int row=TPinjam.getSelectedRow();
        System.out.println(row);
        if(row>=0)
            tabModel.removeRow(row);
        else
            JOptionPane.showMessageDialog(this, "Hapus Gagal");

    }//GEN-LAST:event_BHapusActionPerformed

    private void BSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSimpanActionPerformed

                       try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            conn=DriverManager.getConnection("jdbc:odbc:TPP10");
            if(txtNama.getText().isEmpty() || tabModel.getRowCount()==0 ){
                JOptionPane.showMessageDialog(this,"Silahkan Input Anggota dan Buku");
            } else {
                // Menyimpan ke Tabel Pinjam
                String sql="insert into Pinjam values(?,?,?)";
                PreparedStatement st=conn.prepareStatement(sql);
                st.setString(1,txtNoPinjam.getText());
                st.setString(2,txtTglPinjam.getText());
                st.setString(3,txtNoAnggota.getText());
                int rs= st.executeUpdate();

                String KodeBuku; int rs2=0;
                int jum=tabModel.getRowCount();
                for(int i=0;i<jum;i++){
                    // Menyimpan Ke detail Pinjam
                    String sql2="insert into DetailPinjam values(?,?,?)";
                    PreparedStatement st2=conn.prepareStatement(sql2);
                    KodeBuku = tabModel.getValueAt(i, 0).toString();
                    st2.setString(1,txtNoPinjam.getText());
                    st2.setString(2,KodeBuku);
                    st2.setString(3,"0");
                    rs2= st2.executeUpdate();
                    // Merubah status Buku
                    String sql3="update Buku set Status=? where KodeBuku=?";
                    PreparedStatement st3=conn.prepareStatement(sql3);
                    st3.setString(1,"Dipinjam");
                    st3.setString(2,KodeBuku);
                    st3.executeUpdate();
                }
                if((rs>0) && (rs2>0)){
                    JOptionPane.showMessageDialog(this,"Input Berhasil");
                    Kosongkan();
                } else
                    JOptionPane.showMessageDialog(this,"Input Gagal");
                conn.close();
            }

        } // akhir try
        catch(Exception e){
            System.out.println("Exception " +e );

        }

    }//GEN-LAST:event_BSimpanActionPerformed

    private void BTambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTambah1ActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
        Date tgl_sekarang =new Date();
        SimpleDateFormat format=new SimpleDateFormat("dd/MM/yyyy");
        String tgl=format.format(tgl_sekarang);
        txtTglPinjam.setText(tgl);

        txtNoPinjam.setEnabled(true);
        txtNoAnggota.setEnabled(true);
        txtKodeBuku.setEnabled(true);

    }//GEN-LAST:event_BTambah1ActionPerformed

    private void BBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBatalActionPerformed
        // TODO add your handling code here:
                Kosongkan();
    }//GEN-LAST:event_BBatalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                String reportSource;
         String reportDest = null;

           Map<String,Object> param=new HashMap<String,Object>();


        try{

            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            conn=DriverManager.getConnection("jdbc:odbc:TPP10");

            reportSource=System.getProperty("user.dir")+"/laporan/Peminjaman.jrxml";
            reportDest=System.getProperty("user.dir")+"/laporan/Peminjaman.html";

            JasperReport jasperReport=JasperCompileManager.compileReport(reportSource);
            JasperPrint jasperPrint=JasperFillManager.fillReport(jasperReport,param,conn);

            JasperExportManager.exportReportToHtmlFile(jasperPrint,reportDest);

            JasperViewer.viewReport(jasperPrint,false);

        }catch(Exception e){
        System.out.println(e);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void BCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCloseActionPerformed
        // TODO add your handling code here:
           int selectedOption = JOptionPane.showConfirmDialog(null,
 "Apakah anda akan menutup form peminjaman?", "Tutup Aplikasi", JOptionPane.YES_NO_OPTION);
 if (selectedOption == JOptionPane.YES_OPTION) {
dispose();
 }
    }//GEN-LAST:event_BCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FPeminjaman().setVisible(true);
            }
        });
    }

    private void getData(){
  Connection conn;    // import java.sql.connection
  try{
        //Memanggil Driver
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        //Membuat variabel bertipe Connection
        //Kelas Connection berfungsi menyimpan sebuah koneksi yang sudah dilakukan oleh DriverManger
        conn=DriverManager.getConnection("jdbc:odbc:TPP10");   // import java.sql.DriverManager
        //Membuat Variabel bertipe kelas  PreparedStatement
        //Kelas PreparedStatement berfungsi mengirimkan statement Query Ke Database
        String sql="Select * from Pinjam,DetailPinjam,Buku";
        
        PreparedStatement st=conn.prepareStatement(sql);  // import java.sql.PreparedStatement
        //Membuat Variabel Bertipe ResulSet
        //Kelas Resultset Berfungsi Menyimpan Dataset(Sekumpulan Data) hasil prepareStatement Query
        ResultSet rs=st.executeQuery();   // import java.sql.ResultSet;

       // Menampilkan ke JTable  melalui tabModel
        String NoPinjam,TglPinjam,NoAnggota,KodeBuku,JudulBuku,Status;
        int no=0;
        while(rs.next()){
         no=no+1;

         NoPinjam=rs.getString("NoPinjam");
         TglPinjam=rs.getString("TglPinjam");
         NoAnggota=rs.getString("NoAnggota");
         KodeBuku=rs.getString("KodeBuku");
         JudulBuku=rs.getString("JudulBuku");
         Status=rs.getString("Status");  
         Object Data[]={no,NoPinjam,TglPinjam,NoAnggota,KodeBuku,JudulBuku,Status};
         tabModel.addRow(Data);
        }
          // Tutup Koneksi
          st.close();
          conn.close();
    }
    catch (ClassNotFoundException cnfe) {         // Ketika Gagal Memanggil Driver
           System.out.println("Class Driver tidak ditemukan.. : " + cnfe);
           System.exit(0);
    }
    catch (SQLException sqle) {                   // Ketika Gagal Sql   // import java.sql.SQLException
           System.out.println("Proses Query Gagal = " + sqle);
           System.exit(0);
    }
    catch(Exception e){
           System.out.println("Koneksi Access Gagal " +e.getMessage());
           System.exit(0);
    }
    }    // Akhir Method getData
    
    private void setJTable(){
        String [] JudulKolom={"Kode Buku","Judul"};
    tabModel = new DefaultTableModel(null, JudulKolom){
                  boolean[] canEdit = new boolean [] { false, false };
                  @Override
                  public boolean isCellEditable(int rowIndex, int columnIndex) {
                   return canEdit [columnIndex];
                  }
              };
    TPinjam.setModel(tabModel);
    TPinjam.getColumnModel().getColumn(0).setPreferredWidth(100);
    TPinjam.getColumnModel().getColumn(1).setPreferredWidth(100);
   
}

    private void Kosongkan(){
     txtNoPinjam.setText("");
     txtNoAnggota.setText("");
     txtTglPinjam.setText("");
     txtNama.setText("");
     txtKodeBuku.setText("");
     txtJudulBuku.setText("");
     txtStatus.setText("");

     int row=tabModel.getRowCount();
     for(int i=0;i<row;i++){
         tabModel.removeRow(0);
     }

     txtNoPinjam.setEnabled(false);
     txtNoAnggota.setEnabled(false);
     txtKodeBuku.setEnabled(false);

 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBatal;
    private javax.swing.JButton BClose;
    private javax.swing.JButton BHapus;
    private javax.swing.JButton BSimpan;
    private javax.swing.JButton BTambah;
    private javax.swing.JButton BTambah1;
    private javax.swing.JLabel Judul;
    private javax.swing.JLabel KodeBuku;
    private javax.swing.JLabel Nama;
    private javax.swing.JLabel NoAnggota;
    private javax.swing.JLabel NoPinjam;
    private javax.swing.JLabel Status;
    private javax.swing.JTable TPinjam;
    private javax.swing.JLabel TglPinjam;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private p10516133.peminjaman peminjaman1;
    private p10516133.peminjaman peminjaman2;
    private javax.swing.JTextField txtJudulBuku;
    private javax.swing.JTextField txtKodeBuku;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoAnggota;
    private javax.swing.JTextField txtNoPinjam;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtTglPinjam;
    // End of variables declaration//GEN-END:variables
}
